version: '3.8'

services:

  profile_management:
    command: sh -c "cd /app
      && symfony console d:m:m
      && frankenphp run --config /etc/caddy/Caddyfile --watch"
    volumes:
      - ./app:/app
      - ./php.ini:/usr/local/etc/php/php.ini
      - vendor:/app/vendor:delegated
      - var:/app/var:delegated

volumes:
  vendor:
  var: