version: '3'

services:

  profile_management:
    command: bash -c "cd /app
      && frankenphp run --config /etc/caddy/Caddyfile --watch
      && symfony console d:m:m
      && symfony console importmap:install"
    volumes:
      - ./app:/app
      - vendor:/app/vendor
      - var:/app/var

volumes:
  vendor:
  var: