version: '3.8'

services:

  symfony:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_NAME: ${SERVER_NAME:-localhost}
    depends_on:
      - database

  database:
    image: postgres:alpine3.19
    container_name: database_profile_management
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432"