version: '3.8'

services:

  symfony:
    command: bash -c "cd /app
      && frankenphp run --config /etc/caddy/Caddyfile --watch"
    volumes:
      - ./app:/app
      - vendor:/app/vendor
      - var:/app/var

volumes:
  vendor:
  var: